/* Generated By:JJTree: Do not edit this line. build\gensrc\com\sun\tlddoc\tagfileparser\TagFileTreeConstants.java */

package com.sun.tlddoc.tagfileparser;

public interface TagFileTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTJSPTAGDEF = 1;
  public int JJTCOMMENT = 2;
  public int JJTJSPDIRECTIVE = 3;
  public int JJTJSPDIRECTIVENAME = 4;
  public int JJTJSPATTRIBUTENAME = 5;
  public int JJTJSPATTRIBUTEVALUE = 6;
  public int JJTXMLDIRECTIVE = 7;
  public int JJTXMLDIRECTIVENAME = 8;
  public int JJTXMLATTRIBUTENAME = 9;
  public int JJTXMLATTRIBUTEVALUE = 10;
  public int JJTOTHERCONTENT = 11;


  public String[] jjtNodeName = {
    "Input",
    "JSPTagDef",
    "Comment",
    "JSPDirective",
    "JSPDirectiveName",
    "JSPAttributeName",
    "JSPAttributeValue",
    "XMLDirective",
    "XMLDirectiveName",
    "XMLAttributeName",
    "XMLAttributeValue",
    "OtherContent",
  };
}
