/* Generated By:JJTree&JavaCC: Do not edit this line. TagFileConstants.java */
package com.sun.tlddoc.tagfileparser;

public interface TagFileConstants {

  int EOF = 0;
  int JSP_COMMENT = 1;
  int JSP_DIRECTIVE = 2;
  int XML_DIRECTIVE = 3;
  int OTHER_CONTENT = 4;
  int JSP_DIRECTIVE_NAME = 8;
  int EQ = 10;
  int BEGIN_QUOTE_SINGLE = 11;
  int BEGIN_QUOTE_DOUBLE = 12;
  int END_DIRECTIVE = 13;
  int JSP_ATTRIBUTE_NAME = 14;
  int END_QUOTE_SINGLE = 16;
  int JSP_ATTRIBUTE_VALUE1 = 17;
  int END_QUOTE_DOUBLE = 19;
  int JSP_ATTRIBUTE_VALUE2 = 20;
  int XML_DIRECTIVE_NAME = 22;
  int X_EQ = 24;
  int X_BEGIN_QUOTE_SINGLE = 25;
  int X_BEGIN_QUOTE_DOUBLE = 26;
  int X_END_DIRECTIVE = 27;
  int XML_ATTRIBUTE_NAME = 28;
  int X_END_QUOTE_SINGLE = 30;
  int XML_ATTRIBUTE_VALUE1 = 31;
  int X_END_QUOTE_DOUBLE = 33;
  int XML_ATTRIBUTE_VALUE2 = 34;

  int DEFAULT = 0;
  int WithinComment = 1;
  int JSPDirectiveName = 2;
  int JSPDirectiveAttributeName = 3;
  int JSPDirectiveAttributeValueSingle = 4;
  int JSPDirectiveAttributeValueDouble = 5;
  int XMLDirectiveName = 6;
  int XMLDirectiveAttributeName = 7;
  int XMLDirectiveAttributeValueSingle = 8;
  int XMLDirectiveAttributeValueDouble = 9;
  int WithinOtherContent = 10;

  String[] tokenImage = {
    "<EOF>",
    "\"<%--\"",
    "\"<%@\"",
    "\"<jsp:directive.\"",
    "<OTHER_CONTENT>",
    "\"--%>\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "<JSP_DIRECTIVE_NAME>",
    "<token of kind 9>",
    "\"=\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"%>\"",
    "<JSP_ATTRIBUTE_NAME>",
    "<token of kind 15>",
    "\"\\\'\"",
    "<JSP_ATTRIBUTE_VALUE1>",
    "<token of kind 18>",
    "\"\\\"\"",
    "<JSP_ATTRIBUTE_VALUE2>",
    "<token of kind 21>",
    "<XML_DIRECTIVE_NAME>",
    "<token of kind 23>",
    "\"=\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"/>\"",
    "<XML_ATTRIBUTE_NAME>",
    "<token of kind 29>",
    "\"\\\'\"",
    "<XML_ATTRIBUTE_VALUE1>",
    "<token of kind 32>",
    "\"\\\"\"",
    "<XML_ATTRIBUTE_VALUE2>",
    "\"<\"",
    "<token of kind 36>",
    "<token of kind 37>",
  };

}
